### ISSUE TITLE
Project is misnamed.

### ISSUE THREAD

**Issue by mingwandroid** [conda-forge/scp-feedstock#8]
This should be called scp.py IMHO.

**Comment by remram44** [comment]
The project is called `scp` [on PyPI](https://pypi.python.org/pypi/scp), and that's also the name of the module. I don't see a reason to rename it just because that's the name of the upstream GitHub repo. Most feedstocks are not decorated such.

**Comment by mingwandroid** [comment]
scp is a program that is part of openssl. They got there first and that should be respected.

**Comment by mingwandroid** [comment]
We provide more than just Python packages and therefore have to consider names on a different basis to pypi.

**Comment by remram44** [comment]
I see. That seems fair to me, since conda only has a flat namespace for all languages.

However it's not clear whether this is the upstream author's preferred name (he refers to it as `scp`, `scp.py` is just the name of the GitHub repository). A `python-` prefix also seems common in the ecosystem.

Updating the package name will also break dependent packages, I'm not sure how you can handle this safely (at least a different `scp` package is not showing up right away, but I don't think there's a way for anaconda.org to show deprecation warnings?)

**Comment by ocefpaf** [comment]
The ship has sailed. It is unfortunate that we never got the naming conventions but now, if we ever add the `scp` cli we will need to rename it.
